### PR TITLE
Chris/moreviews

### PR DESCRIPTION
**Pull request by ckim7**

### CODE REVIEW

**Comment by sofiadray** [comment]
the merge conflict info needs to be deleted

**Comment by ckim7** [comment]
-made the changes from josh's comments
-sorted out merge conflicts
-pushed new work on post views+controller (sorry the ones in prior push weren't complete but these tested and work in browser)

**Comment by ckim7** [comment]
the warning for merge conflict is still there but when i check in command line it says up to date ?

**Comment by dragoBK76** [comment]
:shipit:

**Comment by sofiadray** [comment]
cool and if 
@charity.update_attributes(charity_params) 
can just be @charity.save and smae for posts but thats not a vital change

**Comment by sofiadray** [comment]
:shipit:

**Pull request merged**
